export default {
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  LOAD_CATEGORIES: 'LOAD_CATEGORIES',
  LOAD_PRODUCTS_SUCCESS: 'LOAD_PRODUCTS_SUCCESS',
  LOAD_CATEGORIES_SUCCESS: 'LOAD_CATEGORIES_SUCCESS',
  API_URL_DEV: 'http://localhost:3000/api/',
  SELECTED: 'selected',
  URL_CHANGE: 'URL_CHANGE'
};